ArmaForces/ArmaServerManager

ArmaServerManager/Program.cs, ArmaServerManager/settings.json, ArmaServerManagerTests/ArmaServerManagerTests.csproj, ArmaServerManagerTests/SettingsTests.cs, ArmaServerManagerTests/UnitTest1.cs
=> Implement basic Server class

ArmaServerManager/IConfig.cs, ArmaServerManager/ModsetConfig.cs, ArmaServerManager/Server.cs, ArmaServerManager/ServerConfig.cs, ArmaServerManagerTests/ModsetConfigTests.cs, ArmaServerManagerTests/ServerConfigTests.cs
=> Server startup params

.github/workflows/dotnet-core-test.yml
Tests will be run on each PR and push to master.
=> Create tests workflow

.github/workflows/dotnet-core-test.yml, README.md
=> Add readme and rename CI job

Arma.Server.Manager/Controller/ConfigurationController.cs, Arma.Server.Manager/Controller/ModsController.cs, Arma.Server.Manager/Controller/ServerController.cs, Arma.Server.Manager/Features/Configuration/IServerConfigurationLogic.cs, Arma.Server.Manager/Features/Configuration/ServerConfigurationLogic.cs, Arma.Server.Manager/Features/Hangfire/HangfireManager.cs, Arma.Server.Manager/Features/Hangfire/IHangfireManager.cs, Arma.Server.Manager/Features/Mods/ModsManager.cs, Arma.Server.Manager/Features/Server/DTOs/ModsUpdateRequest.cs, Arma.Server.Manager/Features/Server/DTOs/ServerStartRequest.cs, Arma.Server.Manager/Features/Server/DTOs/ServerStatus.cs, Arma.Server.Manager/Providers/Server/IServerProvider.cs, Arma.Server.Manager/Providers/Server/ServerProvider.cs, Arma.Server.Manager/Services/IModsUpdateService.cs, Arma.Server.Manager/Services/ModsUpdateService.cs, Arma.Server.Manager/Startup.cs, Arma.Server.Test/Features/Server/DedicatedServerTests.cs, Arma.Server/Features/Server/DedicatedServer.cs, Arma.Server/Features/Server/IDedicatedServer.cs
- Add `ServerController` which allows to check server status and schedule server startup with given modset name.
- Add `ModsController` which allows to schedule modset or all mods update.
- Add `ConfigurationController` which allows to retrieve and upload config files for both server and modset.
=> Create Server, Mods and Configuration Controllers

Arma.Server.Manager/Pages/Configuration.cshtml, Arma.Server.Manager/Pages/Configuration.cshtml.cs, Arma.Server.Manager/Pages/Shared/_Layout.cshtml, Arma.Server/Config/ISettings.cs, Arma.Server/Config/Settings.cs
- Allow to view current manager configuration through web interface
- Allow edition of manager configuration through web interface
=> Add Manager configuration page

Arma.Server.Manager/Features/Steam/Content/ContentDownloader.cs, Arma.Server.Manager/Features/Steam/Content/Exceptions/WorkshopItemNotExistsException.cs
- Filter out local mods before downloading
- Add sensible exception when workshop item does not exists
=> Throw sensible exception when workshop item does not exists

Arma.Server/Config/ModsetConfig.cs
=> Fix modset config not being applied on top of server config

Arma.Server.Manager/Clients/Modsets/Entities/WebModset.cs, Arma.Server.Manager/Features/Mods/IModsCache.cs, Arma.Server.Manager/Features/Mods/ModsCache.cs, Arma.Server.Manager/Providers/ModsetProvider.cs, Arma.Server.Manager/Startup.cs
- Implement `WebModset` to `IModset` mapping in `ModsetProvider` using `ModsCache`
=> Map WebModset to cache mods in ModsetProvider

Arma.Server.Manager/Pages/Mods.cshtml, Arma.Server.Manager/Pages/Mods.cshtml.cs, Arma.Server.Manager/Pages/Shared/_Layout.cshtml
- Add web page for viewing ModsCache
=> Create mods page for viewing ModsCache

Arma.Server.Manager/Pages/Server.cshtml, Arma.Server.Manager/Pages/Server.cshtml.cs, Arma.Server.Manager/Pages/Shared/_Layout.cshtml, Arma.Server.Manager/Services/ServerStartupService.cs
- Add basic page allowing to start server with selected modset or for selected mission.
=> Server page

Arma.Server.Manager.Test/Features/Mods/ModsManagerTests.cs, Arma.Server.Manager/Clients/Missions/ApiMissionsClient.cs, Arma.Server.Manager/Clients/Modsets/ApiModsetClient.cs, Arma.Server.Manager/Features/Configuration/ServerConfigurationLogic.cs, Arma.Server.Manager/Features/Hangfire/HangfireManager.cs, Arma.Server.Manager/Features/Hangfire/Helpers/HangfireBackgroundJobClient.cs, Arma.Server.Manager/Features/Hangfire/Helpers/HangfireJobStorage.cs, Arma.Server.Manager/Features/Mods/ModsCache.cs, Arma.Server.Manager/Features/Steam/Content/ContentVerifier.cs, Arma.Server.Manager/Services/IMissionPreparationService.cs, Arma.Server.Manager/Services/IServerStartupService.cs, Arma.Server.Manager/Services/MaintenanceService.cs, Arma.Server.Manager/Services/MissionPreparationService.cs, Arma.Server.Manager/Services/ServerStartupService.cs, Arma.Server.Manager/Startup.cs, Arma.Server/Providers/Configuration/ServerConfigurationProvider.cs
- Cleanup unnecessary code, use DI implementations where applicable
=> Remove unnecessary stuff from DI

ArmaForces.ArmaServerManager/Startup.cs
=> Disable anti forgery token for Hangfire Dashboard

ArmaForces.ArmaServerManager/Controller/ModsController.cs, ArmaForces.ArmaServerManager/Features/Hangfire/HangfireManager.cs, ArmaForces.ArmaServerManager/Features/Hangfire/Helpers/HangfireBackgroundJobClient.cs, ArmaForces.ArmaServerManager/Features/Hangfire/Helpers/IHangfireBackgroundJobClient.cs, ArmaForces.ArmaServerManager/Features/Hangfire/IHangfireManager.cs
- Schedule server shutdown job before updating mods
=> Schedule updateMods job after shutdown job from mods controller

ArmaForces.Arma.Server/example_basic.cfg, ArmaForces.Arma.Server/example_server.cfg
- title
- made them in sync with what's used on our server
=> Update example server configs provided with manager

ArmaForces.ArmaServerManager/Extensions/ModExtensions.cs, ArmaForces.ArmaServerManager/Features/Mods/ModDirectoryFinder.cs, ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
- Update mods names, types etc. in cache after retrieving them from mods API
=> Update mod data in cache during mapping web modset to cache mods

ArmaForces.ArmaServerManager/Controller/ServerController.cs
=> Schedule startServer job after shutdown job from server controller

ArmaForces.ArmaServerManager.Tests/Features/Missions/Extensions/WebMissionsCollectionExtensionsTests.cs, ArmaForces.ArmaServerManager.Tests/Helpers/Missions/WebMissionsHelper.cs, ArmaForces.ArmaServerManager/Features/Missions/Extensions/WebMissionsCollectionExtensions.cs, ArmaForces.ArmaServerManager/Services/MissionPreparationService.cs
Fixes starting server with latest mission instead of the nearest one.
=> Fix nearest mission being latest one

ArmaForces.Arma.Server/Features/Mods/IMod.cs, ArmaForces.Arma.Server/Features/Mods/Mod.cs, ArmaForces.ArmaServerManager.Tests/Extensions/ModExtensionsTests.cs, ArmaForces.ArmaServerManager/Extensions/ModExtensions.cs, ArmaForces.ArmaServerManager/Features/Mods/ModsManager.cs, ArmaForces.ArmaServerManager/Features/Steam/Content/ContentDownloader.cs
Removed ManifestId caching, allows mods to update correctly.
=> Fix mods not updating

ArmaForces.Arma.Server/Providers/Keys/KeysProvider.cs
This makes it much easier to find what went wrong.
=> Log Error on exception when copying keys

ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
This is purely cosmetical upgrade, allows for more convenient browsing of cache file.
=> Indent mods cache file

ArmaForces.Arma.Server/example_server.cfg
- title
```
0: all scripts are forbidden
1: only attributes are allowed (including custom attributes added by mods)
2: all scripts are allowed including init scripts
```
=> Enable Zeus composition init scripts in server config

ArmaForces.Arma.Server/Features/Mods/ModType.cs, ArmaForces.Arma.Server/Features/Modsets/Modset.cs
- Fix Optional mods not loaded by server
- Add documentation for ModType
=> Fix optional mods not loaded on server

ArmaForces.ArmaServerManager/Features/Steam/Content/ContentDownloader.cs, ArmaForces.ArmaServerManager/Services/ServerStartupService.cs
Some improvements to Information logging.
- Log for each mod downloaded out of pending download (1/20, 2/20, etc.)
- Server port and modset logged as last log in ServerStart
=> Information logging improvements
