- ArmaServerManager/ArmaServerManager.csproj
- ArmaServerManager/Modset.cs
- ArmaServerManager/Program.cs
- ArmaServerManager/Properties/launchSettings.json
- ArmaServerManager/Server.cs
- ArmaServerManager/ServerConfig.cs
- ArmaServerManager/ServerConfigReplacer.cs
- ArmaServerManager/Settings.cs
- ArmaServerManager/example_basic.cfg
- ArmaServerManager/example_common.Arma3Profile
- ArmaServerManager/example_common.json
- ArmaServerManager/example_server.cfg
- ArmaServerManager/settings.json
- ArmaServerManagerTests/ArmaServerManagerTests.csproj
- ArmaServerManagerTests/ServerConfigReplacerTests.cs
- ArmaServerManagerTests/ServerConfigTests.cs
- ArmaServerManagerTests/ServerTests.cs
- ArmaServerManagerTests/SettingsTests.cs
Server configuration is prepared for given modset:
- First we make sure default configuration is present. If not, we copy it and create `serverConfig` directory.
- Next we check if there is modset specific directory and config present. If not new one gets created, only with `hostName` entry created from pattern given in `hostNamePattern` environmental variable and modset name, eg. for pattern: `Arma {0} Server` and `default` modset name we get `Arma default server`.
- Then we merge modset specific `config.json` on top of `common.json` so it overwrites where needed.
- Next up we fill `server.cfg` and `basic.cfg` with values from builded configuration. `ServerConfig.ReplaceValues()` is used for each key-value replacement separately.
> Implement server config

- Arma.Server.Manager/Program.cs
- Arma.Server.Manager/settings.json
- Arma.Server.Test/Arma.Server.Test.csproj
- Arma.Server.Test/Config/ConfigReplacerTests.cs
- Arma.Server.Test/Config/ModsetConfigTests.cs
- Arma.Server.Test/Config/ServerConfigTests.cs
- Arma.Server.Test/Config/SettingsTests.cs
- Arma.Server.Test/EnumConvert.cs
- Arma.Server.Test/Mod/DeserializationTests.cs
- Arma.Server.Test/Mod/ModSourceTests.cs
- Arma.Server.Test/Mod/ModTypeTests.cs
- Arma.Server.Test/Modlist/DeserializationTests.cs
- Arma.Server.Test/ServerTests.cs
- Arma.Server/Arma.Server.csproj
- Arma.Server/Config/IConfig.cs
- Arma.Server/Config/IModlistConfig.cs
- Arma.Server/Config/IRegistryReader.cs
- Arma.Server/Config/ISettings.cs
- Arma.Server/Config/ModlistConfig.cs
- Arma.Server/Config/RegistryReader.cs
- Arma.Server/Config/ServerConfig.cs
- Arma.Server/Config/Settings.cs
- Arma.Server/Mod/Mod.cs
- Arma.Server/Modlist/Modlist.cs
- Arma.Server/Server.cs
> Configuration refactor

- Arma.Server.Test/Config/ConfigReplacerTests.cs
- Arma.Server.Test/test_server.cfg
- Arma.Server/Config/ConfigReplacer.cs
_Technically it was not a bug because everything worked, just formatting was broken._
> Add missing ConfigReplacer tests and fix bug

- Arma.Server.Manager.Test/Extensions/DateTimeExtensionsTests.cs
- Arma.Server.Manager.Test/Features/Hangfire/HangfireManagerTests.cs
- Arma.Server.Manager.Test/Helpers/Dummy/DummyClass.cs
- Arma.Server.Manager/Extensions/DateTimeExtensions.cs
- Arma.Server.Manager/Features/Hangfire/HangfireManager.cs
- Arma.Server.Manager/Features/Hangfire/Helpers/HangfireBackgroundJobClient.cs
- Arma.Server.Manager/Features/Hangfire/Helpers/HangfireJobStorage.cs
- Arma.Server.Manager/Features/Hangfire/Helpers/IHangfireBackgroundJobClient.cs
- Arma.Server.Manager/Features/Hangfire/Helpers/IHangfireJobStorage.cs
- Arma.Server.Manager/Features/Hangfire/IHangfireManager.cs
- Arma.Server.Manager/Program.cs
- ArmaServerManager.sln.DotSettings
> Hangfire manager with advanced jobs scheduling

- Arma.Server.Manager.Test/Arma.Server.Manager.Test.csproj
- Arma.Server.Manager.Test/Clients/Steam/SteamClientTests.cs
- Arma.Server.Manager.Test/Helpers/Dummy/DummyClass.cs
- Arma.Server.Manager.Test/Mods/ModsManagerTests.cs
- Arma.Server.Manager.Web/Arma.Server.Manager.Web.csproj
- Arma.Server.Manager/Arma.Server.Manager.csproj
- Arma.Server.Manager/Clients/Steam/IModsDownloader.cs
- Arma.Server.Manager/Clients/Steam/ISteamClient.cs
- Arma.Server.Manager/Clients/Steam/ModsDownloader.cs
- Arma.Server.Manager/Clients/Steam/SteamClient.cs
- Arma.Server.Manager/Features/Hangfire/HangfireManager.cs
- Arma.Server.Manager/Features/Hangfire/Helpers/HangfireBackgroundJobClient.cs
- Arma.Server.Manager/Features/Hangfire/Helpers/HangfireJobStorage.cs
- Arma.Server.Manager/Mods/IModsCache.cs
- Arma.Server.Manager/Mods/ModsCache.cs
- Arma.Server.Manager/Mods/ModsManager.cs
- Arma.Server.Manager/Program.cs
- Arma.Server.Manager/Services/ModsUpdateService.cs
- Arma.Server.Test/Arma.Server.Test.csproj
- Arma.Server/Arma.Server.csproj
- Arma.Server/Config/Settings.cs
- ArmaServerManager.sln.DotSettings
> Rework mods downloader

- Arma.Server.Test/Providers/Parameters/HeadlessParametersProviderTests.cs
- Arma.Server/Config/IModsetConfig.cs
- Arma.Server/Config/ModsetConfig.cs
- Arma.Server/Mod/Mod.cs
- Arma.Server/Providers/Parameters/HeadlessParametersProvider.cs
- Add `ServerPassword` to `ModsetConfig`
- Use `ServerPassword` in `HeadlessClientParametersProvider`
> Add Headless Client password parameter

- Arma.Server.Manager.Test/Features/Mods/ModsManagerTests.cs
- Arma.Server.Manager/Constants/SteamConstants.cs
- Arma.Server.Manager/Features/Mods/IModsCache.cs
- Arma.Server.Manager/Features/Mods/IModsManager.cs
- Arma.Server.Manager/Features/Mods/ModsCache.cs
- Arma.Server.Manager/Features/Mods/ModsManager.cs
- Arma.Server.Manager/Features/Steam/Content/ContentDownloader.cs
- Arma.Server.Manager/Features/Steam/Content/ContentVerifier.cs
- Arma.Server.Manager/Features/Steam/Content/IContentVerifier.cs
- Arma.Server.Manager/Features/Steam/SteamClient.cs
- Arma.Server.Manager/Startup.cs
- Include mods verification before downloading
- Fix frequent Task Cancelled exceptions when downloading manifests
- Fix frequent Task Cancelled exceptions when retrieving mod download handler
> Fix mods downloading and verifying

- ArmaForces.Arma.Server/Features/Mods/IMod.cs
- ArmaForces.Arma.Server/Features/Mods/Mod.cs
- ArmaForces.Arma.Server/Providers/Parameters/ServerParametersProvider.cs
- ArmaForces.ArmaServerManager.Tests/Features/Mods/ModsCacheTests.cs
- ArmaForces.ArmaServerManager.Tests/Features/Mods/ModsManagerTests.cs
- ArmaForces.ArmaServerManager/Features/Mods/IModDirectoryFinder.cs
- ArmaForces.ArmaServerManager/Features/Mods/IModsCache.cs
- ArmaForces.ArmaServerManager/Features/Mods/ModDirectoryFinder.cs
- ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
- ArmaForces.ArmaServerManager/Features/Mods/ModsManager.cs
- ArmaForces.ArmaServerManager/Features/Modsets/DTOs/WebMod.cs
- ArmaForces.ArmaServerManager/Pages/Mods.cshtml.cs
- Change workshopId to long as int is too small
- Fix mod equality checking
- Use WebMod's directory for local mods (as it was not used before)
- Fix mods startup parameters not including `""` around the argument
- Introduce `IModDirectoryFinder` to extract mod searching logic out of ModsCache.
- Add cDLC support as local mod
- Mod name should be always updated with new data when available
- Added xml documentation to ModsCache and updated existing one
> Add cDLC support as local mod, fixes for mods and modsCache, add docxmls to ModsCache

- ArmaForces.Arma.Server/Features/Server/ServerProcess.cs
- ArmaForces.ArmaServerManager/Extensions/RestClientExtensions.cs
- ArmaForces.ArmaServerManager/Features/Missions/ApiMissionsClient.cs
- ArmaForces.ArmaServerManager/Services/ServerStartupService.cs
- ArmaForces.ArmaServerManager/Startup.cs
- Remove mods update from startup procedure (as it was taking too long, we need verifying through last updated date instead of verifying all files every time).
- Fix server process shutdown not detected correctly.
- Add ModDirectoryFinder to DI (as it was forgotten)
- Fix DateTime format in ApiMissionsClient
- Add more informations to error message when request fails.
> Server start and shutdown fixes and enhancements

- ArmaForces.ArmaServerManager/Startup.cs
This should enforce one job at a time to prevent accidental server startup if mods are being updated.
This is might get superseded when enhanced status with currently executed job is implemented.
> Force one job at a time

- ArmaForces.Arma.Server.Tests/Features/Server/DedicatedServerTests.cs
- ArmaForces.Arma.Server/Features/Server/DTOs/ServerStatus.cs
- ArmaForces.Arma.Server/Features/Server/DTOs/ServerStatusEnum.cs
It will prevent server status reporting server being started and stopped at the same time. And it's clearer.
> Create new server status enum

- ArmaForces.Arma.Server/Features/Mods/ModEqualityComparer.cs
- ArmaForces.ArmaServerManager.Tests/Features/Missions/ApiMissionsClientTests.cs
- ArmaForces.ArmaServerManager/Extensions/HttpStatusCodeExtensions.cs
- ArmaForces.ArmaServerManager/Extensions/RestClientExtensions.cs
- ArmaForces.ArmaServerManager/Extensions/RestResponseExtensions.cs
- ArmaForces.ArmaServerManager/Features/Missions/ApiMissionsClient.cs
- ArmaForces.ArmaServerManager/Features/Missions/IApiMissionsClient.cs
- ArmaForces.ArmaServerManager/Features/Mods/IModsCache.cs
- ArmaForces.ArmaServerManager/Features/Mods/IModsManager.cs
- ArmaForces.ArmaServerManager/Features/Mods/IWebModsetMapper.cs
- ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
- ArmaForces.ArmaServerManager/Features/Mods/ModsManager.cs
- ArmaForces.ArmaServerManager/Pages/Server.cshtml
- ArmaForces.ArmaServerManager/Pages/Server.cshtml.cs
- ArmaForces.ArmaServerManager/Providers/ModsetProvider.cs
- ArmaForces.ArmaServerManager/Services/IModsUpdateService.cs
- ArmaForces.ArmaServerManager/Services/MissionPreparationService.cs
- ArmaForces.ArmaServerManager/Services/ModsUpdateService.cs
- ArmaForces.ArmaServerManager/Services/ServerStartupService.cs
- ArmaForces.ArmaServerManager/Startup.cs
- title
- Add ability to update collection of mods
- Extract `IWebModsetMapper` interface from `IModsCache`
- Reload server page after submitting server startup to prevent user having to reload it himself
Closes #47
> Make server page work when missions API is down

- ArmaForces.Arma.Server/Features/Servers/DTOs/ServerStatus.cs
- ArmaForces.ArmaServerManager/Services/IServerStartupService.cs
- ArmaForces.ArmaServerManager/Services/ServerStartupService.cs
There is no need to return e.g. players count or server name when its stopped. This PR changes all properties other than status enum to nullable and only relevant info will be returned when server is stopped/starting.
> Make server status don't show nulls

- ArmaForces.ArmaServerManager/Features/Steam/Content/ContentVerifier.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/SteamContentConstants.cs
This will:
- Delay download ManifestId attempts by 5 seconds.
- Handle `SteamKit2.AsyncJobFailedException` in a similar way as `TaskCanceledException`.
- Decrease attempts limit to 3 (was 10).
> Delay consecutive ManifestId download attempts and descrease limit to 3

- ArmaForces.ArmaServerManager.Tests/Features/Steam/Content/ContentFileVerifierTests.cs
- ArmaForces.ArmaServerManager/ArmaForces.ArmaServerManager.csproj
- ArmaForces.ArmaServerManager/Features/Mods/ModsManager.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/ContentFileVerifier.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/ContentVerifier.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/IContentFileVerifier.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/IManifestDownloader.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/ManifestDownloader.cs
- ArmaForces.ArmaServerManager/Startup.cs
This will remove all redundant files which are in mod's directory as SteamKit can't remove e.g. old bikeys correctly.
> Remove redundant mod files during mod files verification

- ArmaForces.Arma.Server/example_server.cfg
- title
>Limit for maximum Steam Query packet length. (since Arma 3 v2.00)Increasing this value is dangerous as it can cause Arma server to send UDP packets of a size larger than the MTU. This will cause UDP packets to be fragmented which is not supported by some older routers.But increasing this will fix the modlist length limit in Arma 3 Launcher.
> Increase steamProtocolMaxDataSize in default server config

- ArmaForces.ArmaServerManager/Features/Hangfire/Exceptions/JobFailedException.cs
- ArmaForces.ArmaServerManager/Features/Hangfire/Filters/FailOnResultFailureAttribute.cs
- ArmaForces.ArmaServerManager/Startup.cs
If failed `Result` was returned, the job still succeeded. This PR converts failed results to failed job state.
> Fail job when failure Result is retured

- ArmaForces.Arma.Server.Tests/Features/Servers/DedicatedServerTests.cs
- ArmaForces.Arma.Server/Features/Servers/DedicatedServer.cs
If Manager started and server was already running, the OnShutdown action would not be performed, thus HCs would not be shut down and this could block starting a new server.
> Fix discovered dedicated server shutdown didn't remove server 

- ArmaForces.ArmaServerManager/Providers/Server/ServerProvider.cs
This was caused by removing incorrect server. When server was closed and new one was started, the new one would be removed by OnDispose event handler of the original one. This is now fixed.
> Fix server status returning stopped for restarted server

- ArmaForces.ArmaServerManager/Features/Steam/Content/ContentFileVerifier.cs
- ArmaForces.ArmaServerManager/Features/Steam/Content/ContentVerifier.cs
CBA was updating every time because `userconfig/cba_settings.sqf` has no content and expected hash is zero but the actual was not zero. Now all files (if there are any similar cases) will be considered as up to date if have no content and should have no content.
> Fix CBA always updating

- ArmaForces.ArmaServerManager/Features/Modsets/DTOs/WebDlc.cs
It's already a nullable in Dlc model, probably overlooked.
This caused `JsonSerializationException`:
```
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTime'. Path 'dlcs[0].lastUpdatedAt', line 1, position 8386.
```
> Make LastUpdatedAt nullable in WebDlc

- ArmaForces.ArmaServerManager/Startup.cs
Now when requesting status when server is stopped, we don't get all properties with nulls.
> Ignore null values when serializing

- ArmaForces.ArmaServerManager/Startup.cs
This is for our fellas who use browser to view server status, but their browser sucks and shows them raw, unformatted JSON. We may remove this once we create proper server status page.
> Add indentation to API responses

- ArmaForces.ArmaServerManager/Infrastructure/Authentication/ApiKeyAttribute.cs
Now it'll be possible to check what exactly was executed.
> Add route and request parameters logging along with API Key

- ArmaForces.ArmaServerManager.Tests/Features/Mods/ModsManagerUnitTests.cs
- ArmaForces.ArmaServerManager/Api/Jobs/DTOs/JobScheduleRequestDto.cs
- ArmaForces.ArmaServerManager/Api/Mods/ModsController.cs
- ArmaForces.ArmaServerManager/Api/Status/DTOs/AppStatus.cs
- ArmaForces.ArmaServerManager/Features/Mods/DependencyInjection/ModsServiceCollectionExtensions.cs
- ArmaForces.ArmaServerManager/Features/Mods/IModsManager.cs
- ArmaForces.ArmaServerManager/Features/Mods/ModsManager.cs
- ArmaForces.ArmaServerManager/Features/Status/AppStatusStore.cs
- ArmaForces.ArmaServerManager/Features/Status/StatusProvider.cs
- ArmaForces.ArmaServerManager/Features/Steam/RemoteStorage/ISteamRemoteStorage.cs
- ArmaForces.ArmaServerManager/Properties/launchSettings.json
- ArmaForces.ArmaServerManager/Services/IModsUpdateService.cs
- ArmaForces.ArmaServerManager/Services/IModsVerificationService.cs
- ArmaForces.ArmaServerManager/Services/MissionPreparationService.cs
- ArmaForces.ArmaServerManager/Services/ModsVerificationService.cs
- ArmaForces.ArmaServerManager/Services/ServerStartupService.cs
- ArmaForces.ArmaServerManager/Startup.cs
- Adds quick check for update during server startup
- Adds ability to manually trigger modset verification (old style detailed update) `api/mods/{modsetName}/verify`
- Removes detailed verification from update mods `api/mods/{modsetName}/update`
- Ability to display more contextual app status, e.g., when app is updating mods before starting up the server, so users will know that's happening instead of just "starting server".
Fixes #86.
> Quick-check mods for updates on server startup using workshop item updated date
